import { EnumType, superenum } from '@ncoderz/superenum';

const ConfigKey = superenum({
  _unknown: '_unknown',

  // 'Tag' Tags

  _tag_title: '_tag_title',
  _tag_anchor: '_tag_anchor',
  _tag_reference: '_tag_reference',
  _tag_property: '_tag_property',
  _tag_itemLead: '_tag_itemLead',
  _tag_instruction: '_tag_instruction',
  _tag_hint: '_tag_hint',
  _tag_true: '_tag_true',
  _tag_false: '_tag_false',
  _tag_sampleSolution: '_tag_sampleSolution',
  _tag_gap: '_tag_gap',
  _tag_mark: '_tag_mark',
  _tag_resource: '_tag_resource',
  _tag_remark: '_tag_remark',
  _tag_comment: '_tag_comment',

  // Property Tags
  _property_action: '_property_action',
  _property_ageRange: '_property_ageRange',
  _property_aiGenerated: '_property_aiGenerated',
  _property_allowSubtitles: '_property_allowSubtitles',
  _property_alt: '_property_alt',
  _property_author: '_property_author',
  _property_autoplay: '_property_autoplay',
  _property_book: '_property_book',
  _property_bot: '_property_bot',
  _property_caption: '_property_caption',
  _property_caseSensitive: '_property_caseSensitive',
  _property_color: '_property_color',
  _property_colorTag: '_property_colorTag',
  _property_computerLanguage: '_property_computerLanguage',
  _property_copyright: '_property_copyright',
  _property_coverImage: '_property_coverImage',
  _property_date: '_property_date',
  _property_deeplink: '_property_deeplink',
  _property_duration: '_property_duration',
  _property_emphasis: '_property_emphasis',
  _property_example: '_property_example',
  _property_externalId: '_property_externalId',
  _property_externalLink: '_property_externalLink',
  _property_externalLinkText: '_property_externalLinkText',
  _property_flashcardSet: '_property_flashcardSet',
  _property_focusX: '_property_focusX',
  _property_focusY: '_property_focusY',
  _property_format: '_property_format',
  _property_height: '_property_height',
  _property_icon: '_property_icon',
  _property_iconTag: '_property_iconTag',
  _property_id: '_property_id',
  _property_imageSource: '_property_imageSource',
  _property_isInfoOnly: '_property_isInfoOnly',
  _property_isTracked: '_property_isTracked',
  _property_kind: '_property_kind',
  _property_labelFalse: '_property_labelFalse',
  _property_labelTrue: '_property_labelTrue',
  _property_language: '_property_language',
  _property_level: '_property_level',
  _property_license: '_property_license',
  _property_list: '_property_list',
  _property_location: '_property_location',
  _property_longAnswer: '_property_longAnswer',
  _property_markConfig: '_property_markConfig',
  _property_mark: '_property_mark',
  _property_mockupId: '_property_mockupId',
  _property_mute: '_property_mute',
  _property_padletId: '_property_padletId',
  _property_partialAnswer: '_property_partialAnswer',
  _property_partner: '_property_partner',
  _property_posterImage: '_property_posterImage',
  _property_progress: '_property_progress',
  _property_publications: '_property_publications',
  _property_publisher: '_property_publisher',
  _property_quotedPerson: '_property_quotedPerson',
  _property_reaction: '_property_reaction',
  _property_reference: '_property_reference',
  _property_releaseVersion: '_property_releaseVersion',
  _property_sampleSolution: '_property_sampleSolution',
  _property_shortAnswer: '_property_shortAnswer',
  _property_showInIndex: '_property_showInIndex',
  _property_showSubtitles: '_property_showSubtitles',
  _property_siteName: '_property_siteName',
  _property_size: '_property_size',
  _property_spaceId: '_property_spaceId',
  _property_src1x: '_property_src1x',
  _property_src2x: '_property_src2x',
  _property_src3x: '_property_src3x',
  _property_src4x: '_property_src4x',
  _property_subject: '_property_subject',
  _property_subtype: '_property_subtype',
  _property_tag: '_property_tag',
  _property_target: '_property_target',
  _property_textReference: '_property_textReference',
  _property_theme: '_property_theme',
  _property_thumbImage: '_property_thumbImage',
  _property_toc: '_property_toc',
  _property_trim: '_property_trim',
  _property_type: '_property_type',
  _property_videoCallLink: '_property_videoCallLink',
  _property_width: '_property_width',

  // Resources
  _resource_image: '_resource_image',
  // _resource_imageResponsive: '_resource_imageResponsive',
  _resource_imagePortrait: '_resource_imagePortrait',
  _resource_imageLandscape: '_resource_imageLandscape',
  _resource_imageEmbed: '_resource_imageEmbed',
  _resource_imageLink: '_resource_imageLink',
  _resource_audio: '_resource_audio',
  _resource_audioEmbed: '_resource_audioEmbed',
  _resource_audioLink: '_resource_audioLink',
  _resource_video: '_resource_video',
  _resource_videoEmbed: '_resource_videoEmbed',
  _resource_videoLink: '_resource_videoLink',
  // _resource_stillImageFilm: '_resource_stillImageFilm',
  _resource_stillImageFilmEmbed: '_resource_stillImageFilmEmbed',
  _resource_stillImageFilmLink: '_resource_stillImageFilmLink',
  _resource_article: '_resource_article',
  _resource_articleEmbed: '_resource_articleEmbed',
  _resource_articleLink: '_resource_articleLink',
  _resource_document: '_resource_document',
  _resource_documentEmbed: '_resource_documentEmbed',
  _resource_documentLink: '_resource_documentLink',
  _resource_documentDownload: '_resource_documentDownload',
  _resource_appLink: '_resource_appLink',
  _resource_websiteLink: '_resource_websiteLink',

  // Groups
  _group_standardAllBits: '_group_standardAllBits',
  _group_standardItemLeadInstructionHint: '_group_standardItemLeadInstructionHint',
  _group_standardExample: '_group_standardExample',
  _group_standardTags: '_group_standardTags',
  _group_imageSource: '_group_imageSource',
  _group_partner: '_group_partner',
  _group_gap: '_group_gap',
  _group_trueFalse: '_group_trueFalse',
  _group_markConfig: '_group_markConfig',
  _group_mark: '_group_mark',
  _group_learningPathCommon: '_group_learningPathCommon',
  _group_resourceCommon: '_group_resourceCommon',
  _group_resourceImageCommon: '_group_resourceImageCommon',
  _group_resourceAudioCommon: '_group_resourceAudioCommon',
  _group_resourceVideoCommon: '_group_resourceVideoCommon',
  _group_resourceImage: '_group_resourceImage',
  _group_resourceImageEmbed: '_group_resourceImageEmbed',
  _group_resourceImageLink: '_group_resourceImageLink',
  _group_resourceImageResponsive: '_group_resourceImageResponsive', // Combo resource
  _group_resourceImagePortrait: '_group_resourceImagePortrait',
  _group_resourceImageLandscape: '_group_resourceImageLandscape',
  _group_resourceAudio: '_group_resourceAudio',
  _group_resourceAudioEmbed: '_group_resourceAudioEmbed',
  _group_resourceAudioLink: '_group_resourceAudioLink',
  _group_resourceVideo: '_group_resourceVideo',
  _group_resourceVideoEmbed: '_group_resourceVideoEmbed',
  _group_resourceVideoLink: '_group_resourceVideoLink',
  _group_resourceStillImageFilm: '_group_resourceStillImageFilm', // Combo resource
  _group_resourceStillImageFilmEmbed: '_group_resourceStillImageFilmEmbed',
  _group_resourceStillImageFilmLink: '_group_resourceStillImageFilmLink',
  _group_resourceArticle: '_group_resourceArticle',
  _group_resourceArticleEmbed: '_group_resourceArticleEmbed',
  _group_resourceArticleLink: '_group_resourceArticleLink',
  _group_resourceDocument: '_group_resourceDocument',
  _group_resourceDocumentEmbed: '_group_resourceDocumentEmbed',
  _group_resourceDocumentLink: '_group_resourceDocumentLink',
  _group_resourceDocumentDownload: '_group_resourceDocumentDownload',
  _group_resourceAppLink: '_group_resourceAppLink',
  _group_resourceWebsiteLink: '_group_resourceWebsiteLink',
});

export type ConfigKeyType = EnumType<typeof ConfigKey>;

export { ConfigKey };
