import { EnumType, superenum } from '@ncoderz/superenum';

const AstNodeTypeRaw = {
  unknown: 'unknown', // unknown

  // Non-terminal
  bitmark: 'bitmark', // bitmark
  bits: 'bits', // bits
  bitsValue: 'bitsValue', // bit
  properties: 'properties',
  property: 'property',
  propertyValues: 'propertyValues',
  itemLead: 'itemLead',
  body: 'body',
  bodyValue: 'bodyValue',
  footer: 'footer',
  gap: 'gap',
  select: 'select',
  highlight: 'highlight',
  elements: 'elements',
  solutions: 'solutions',
  options: 'options',
  optionsValue: 'optionsValue',
  texts: 'texts',
  textsValue: 'textsValue',
  statements: 'statements',
  statementsValue: 'statementsValue',
  choices: 'choices',
  choicesValue: 'choicesValue',
  responses: 'responses',
  responsesValue: 'responsesValue',
  quizzes: 'quizzes',
  quizzesValue: 'quizzesValue',
  heading: 'heading',
  forValues: 'forValues',
  pairs: 'pairs',
  pairsValue: 'pairsValue',
  values: 'values',
  matrix: 'matrix',
  matrixValue: 'matrixValue',
  cells: 'cells',
  cellsValue: 'cellsValue',
  questions: 'questions',
  questionsValue: 'questionsValue',

  resource: 'resource',
  resourceType: 'resourceType',
  imageResource: 'imageResource',
  audioResource: 'audioResource',
  videoResource: 'videoResource',

  // Terminal (leaf)
  markup: 'markup', // bitmark markup
  bitType: 'bitType', // bit type
  attachmentType: 'attachmentType', // bit attachment type
  textFormat: 'textFormat',

  ids: 'ids',
  idsValue: 'idsValue',
  externalIds: 'externalIds',
  externalIdsValue: 'externalIdsValue',
  ageRanges: 'ageRanges',
  ageRangesValue: 'ageRangesValue',
  languages: 'languages',
  languagesValue: 'languagesValue',
  computerLanguages: 'computerLanguages',
  computerLanguagesValue: 'computerLanguagesValue',
  coverImages: 'coverImages',
  coverImagesValue: 'coverImagesValue',
  publishers: 'publishers',
  publishersValue: 'publishersValue',
  publications: 'publications',
  publicationsValue: 'publicationsValue',
  authors: 'authors',
  authorsValue: 'authorsValue',
  dates: 'dates',
  datesValue: 'datesValue',
  locations: 'locations',
  locationsValue: 'locationsValue',
  themes: 'themes',
  themesValue: 'themesValue',
  kinds: 'kinds',
  kindsValue: 'kindsValue',
  actions: 'actions',
  actionsValue: 'actionsValue',
  thumbImages: 'thumbImages',
  thumbImagesValue: 'thumbImagesValue',
  durations: 'durations',
  durationsValue: 'durationsValue',
  deepLinks: 'deepLinks',
  deepLinksValue: 'deepLinksValue',
  externalLink: 'externalLink',
  externalLinkText: 'externalLinkText',
  videoCallLinks: 'videoCallLinks',
  videoCallLinksValue: 'videoCallLinksValue',
  bots: 'bots',
  botsValue: 'botsValue',
  referenceProperties: 'referenceProperties',
  referencePropertiesValue: 'referencePropertiesValue',
  sampleSolutions: 'sampleSolutions',
  sampleSolutionsValue: 'sampleSolutionsValue',
  lists: 'lists',
  listsValue: 'listsValue',
  labelTrue: 'labelTrue',
  labelFalse: 'labelFalse',
  quotedPerson: 'quotedPerson',

  book: 'book',

  item: 'item',
  lead: 'lead',
  hint: 'hint',
  instruction: 'instruction',
  example: 'example',

  title: 'title',
  subtitle: 'subtitle',
  level: 'level',
  toc: 'toc',
  progress: 'progress',
  anchor: 'anchor',
  reference: 'reference',
  referenceEnd: 'referenceEnd',

  bodyText: 'bodyText',
  footerText: 'footerText',
  elementsValue: 'elementsValue',
  solutionsValue: 'solutionsValue',
  prefix: 'prefix',
  postfix: 'postfix',
  isCaseSensitive: 'isCaseSensitive',
  isLongAnswer: 'isLongAnswer',
  isShortAnswer: 'isShortAnswer',
  isCorrect: 'isCorrect',
  forKeys: 'forKeys',
  forValuesValue: 'forValuesValue',
  key: 'key',
  valuesValue: 'valuesValue',
  question: 'question',
  partialAnswer: 'partialAnswer',
  sampleSolution: 'sampleSolution',
  statementText: 'statementText',
  text: 'text',
  propertyKey: 'propertyKey',
  propertyValue: 'propertyValue',
  keyAudio: 'keyAudio',
  keyImage: 'keyImage',

  // Resources
  type: 'type',
  format: 'format',
  url: 'url',
  src: 'src',
  src1x: 'src1x',
  src2x: 'src2x',
  src3x: 'src3x',
  src4x: 'src4x',
  width: 'width',
  height: 'height',
  alt: 'alt',
  license: 'license',
  copyright: 'copyright',
  provider: 'provider',
  showInIndex: 'showInIndex',
  caption: 'caption',
  duration: 'duration',
  posterImage: 'posterImage',
  thumbnails: 'thumbnails',
  thumbnailsValue: 'thumbnailsValue',
} as const;

export type AstNodeTypeKeys = keyof typeof AstNodeTypeRaw;
const AstNodeType = superenum(AstNodeTypeRaw);

export type AstNodeTypeType = EnumType<typeof AstNodeType>;

export { AstNodeType, AstNodeTypeRaw };
