# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish to NPM

on:
  workflow_call:
    secrets:
      CIRCLE_TOKEN:
        required: true
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for OIDC to NPM
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Resolve draft release (GH API, retry)
        id: release_ref
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=$(node -p "require('./package.json').version")
          NAME="v$VERSION"
          OWNER_REPO="${{ github.repository }}"
          for i in 1 2 3 4 5; do
            RELEASE_ID=$(gh api \
              repos/$OWNER_REPO/releases \
              --paginate \
              --jq "map(select(.draft == true and (.name == \"${NAME}\" or .tag_name == \"${NAME}\")))[0].id" \
              --method GET 2>/dev/null)
            if [ -n "$RELEASE_ID" ]; then
              echo "release_id=$RELEASE_ID" >> $GITHUB_OUTPUT
              echo "release_tag=$NAME" >> $GITHUB_OUTPUT
              exit 0
            fi
            echo "Draft release ${NAME} not visible yet, retry $i/5" >&2
            sleep 5
          done
          echo "Draft release ${NAME} not found after retries" >&2
          exit 1

      - name: Publish
        run: npm publish --access public

      - name: Get version from package.json
        id: pkg
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Invalid version format: $VERSION (expected X.X.X)"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

      - name: Mark as Released (creates vX.X.X tag in Git)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            repos/${{ github.repository }}/releases/${{ steps.release_ref.outputs.release_id }} \
            -X PATCH \
            -F draft=false

      - name: Trigger bitmark API pipeline
        env:
          CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Circle-Token: $CIRCLE_TOKEN" \
            https://circleci.com/api/v2/project/github/getMoreBrain/bitbook-api/pipeline

      - name: Purge jsdelivr cache
        run: |
          curl -X GET \
            https://purge.jsdelivr.net/npm/@gmb/bitmark-parser-generator@latest/dist/browser/bitmark-parser-generator.min.js
