import { EnumType, superenum } from '@ncoderz/superenum';

const BitBitType = superenum({
  book: 'book',
  chapter: 'chapter',
  summary: 'summary',
  bitAlias: 'bit-alias',
  internalLink: 'internal-link',
  anchor: 'anchor',
  groupBorn: 'group-born',
  groupDied: 'group-died',
  cloze: 'cloze',
  clozeInstructionGrouped: 'cloze-instruction-grouped',
  clozeSolutionGrouped: 'cloze-solution-grouped',
  clozeAndMultipleChoiceText: 'cloze-and-multiple-choice-text',
  multipleChoice: 'multiple-choice',
  multipleChoice1: 'multiple-choice-1',
  multipleChoiceText: 'multiple-choice-text',
  multipleResponse: 'multiple-response',
  multipleResponse1: 'multiple-response-1',
  essay: 'essay',
  interview: 'interview',
  interviewInstructionGrouped: 'interview-instruction-grouped',
  match_: 'match-',
  matchReverse: 'match-reverse',
  matchPicture: 'match-picture',
  matchAudio: 'match-audio',
  matchSolutionGrouped: 'match-solution-grouped',
  trueFalse1: 'true-false-1',
  trueFalse: 'true-false',
  sequence: 'sequence',
  correction: 'correction',
  mark_: 'mark-',
  documentUpload: 'document-upload',
  takePicture: 'take-picture',
  recordAudio: 'record-audio',
  preparationNote: 'preparation-note',
  assignment: 'assignment',
  article: 'article',
  articleAttachment: 'article-attachment',
  flashcard: 'flashcard',
  flashcard1: 'flashcard-1',
  chat: 'chat',
  conversation: 'conversation',
  botInterview: 'bot-interview',
  selfAssessment: 'self-assessment',
  rating: 'rating',
  survey: 'survey',
  survey1: 'survey-1',
  surveyAnonymous: 'survey-anonymous',
  surveyAnonymous1: 'survey-anonymous-1',
  hint: 'hint',
});

export type BitBitTypeType = EnumType<typeof BitBitType>;

export { BitBitType };
