import path from 'path';

const base = 'assets/test/json/';

const rawFiles = {
  learningPath1: 'learning-path1.json',
  learningPath3: 'learning-path3.json',
  resourceAll: 'resource-all.json',
  utfgpun: 'utfgpun.json',
  learningPath4: 'learning-path4.json',
  learningPath5: 'learning-path5.json',
  learningPath6: 'learning-path6.json',
  learningPath7: 'learning-path7.json',
  book1: 'book1.json',
  book2: 'book2.json',
  page1: 'page1.json',
  page2: 'page2.json',
  article1: 'article1.json',
  article2: 'article2.json',
  assign1: 'assign1.json',
  botinterview1: 'botinterview1.json',
  botinterview2: 'botinterview2.json',
  chat1: 'chat1.json',
  chat2: 'chat2.json',
  conversation1: 'conversation1.json',
  cloze: 'cloze.json',
  cloze2: 'cloze2.json',
  cloze3: 'cloze3.json',
  cloze4: 'cloze4.json',
  cloze5: 'cloze5.json',
  cloze10: 'cloze10.json',
  cloze11: 'cloze11.json',
  cloze12: 'cloze12.json',
  cloze13: 'cloze13.json',
  clozeEmoji: 'cloze-emoji.json',
  clozeEmoji2: 'cloze-emoji2.json',
  clozeig: 'clozeig.json',
  clozenmultx: 'clozenmultx.json',
  clozesg1: 'clozesg1.json',
  corr1: 'corr1.json',
  corr2: 'corr2.json',
  corr3: 'corr3.json',
  docup1: 'docup1.json',
  essay1: 'essay1.json',
  essay2: 'essay2.json',
  essay3: 'essay3.json',
  essay4: 'essay4.json',
  essay5: 'essay5.json',
  essay6: 'essay6.json',
  essay7: 'essay7.json',
  essay8: 'essay8.json',
  essay9: 'essay9.json',
  flashcard1: 'flashcard1.json',
  flashcard2: 'flashcard2.json',
  flashcard3: 'flashcard3.json',
  flashcard4: 'flashcard4.json',
  flashcardSet: 'flashcard-set.json',
  interview1: 'interview1.json',
  interview2: 'interview2.json',
  interview3: 'interview3.json',
  interview4: 'interview4.json',
  interview100: 'interview100.json',
  interview101: 'interview101.json',
  interview102: 'interview102.json',
  interview103: 'interview103.json',
  interview104: 'interview104.json',
  interview105: 'interview105.json',
  interview106: 'interview106.json',
  interview107: 'interview107.json',
  interview108: 'interview108.json',
  interview109: 'interview109.json',
  interview110: 'interview110.json',
  interviewImage1: 'interview-image1.json',
  mark1: 'mark1.json',
  mark2: 'mark2.json',
  match1: 'match1.json',
  match2: 'match2.json',
  match3: 'match3.json',
  match4: 'match4.json',
  match5: 'match5.json',
  matchsg1: 'matchsg1.json',
  matchPict1: 'match-pict1.json',
  matchPict2: 'match-pict2.json',
  matchAudio1: 'match-audio1.json',
  matchArticle1: 'match-article1.json',
  matchMatrix1: 'match-matrix1.json',
  matchMatrix3: 'match-matrix3.json',
  multich_1: 'multich-1.json',
  multich_1_2: 'multich-1-2.json',
  multires_1: 'multires-1.json',
  multires_1_2: 'multires-1-2.json',
  multich1: 'multich1.json',
  multich2: 'multich2.json',
  multichtx1: 'multichtx1.json',
  multichtx2: 'multichtx2.json',
  multichtx3: 'multichtx3.json',
  multichtx4: 'multichtx4.json',
  multires1: 'multires1.json',
  multires2: 'multires2.json',
  multitxt1: 'multitxt1.json',
  multitxt2: 'multitxt2.json',
  multitxt3: 'multitxt3.json',
  multitxt4: 'multitxt4.json',
  prepnote1: 'prepnote1.json',
  rec1: 'rec1.json',
  seq1: 'seq1.json',
  seq2: 'seq2.json',
  takepic1: 'takepic1.json',
  truefalse1: 'truefalse1.json',
  truefalse2: 'truefalse2.json',
  truefalse3: 'truefalse3.json',
  truefalse4: 'truefalse4.json',
  truefalse5: 'truefalse5.json',
  selfass1: 'selfass1.json',
  selfass2: 'selfass2.json',
  rating1: 'rating1.json',
  survey1: 'survey1.json',
  surveyAnon1: 'survey-anon1.json',
  highlighttext1: 'highlighttext1.json',
  highlighttext2: 'highlighttext2.json',
  bitAlias1: 'bit-alias1.json',
  sampleSoln: 'sample-soln.json',
  bitAlias2: 'bit-alias2.json',
  blocktags: 'blocktags.json',
  articleOnline: 'article-online.json',
  appresource: 'appresource.json',
  GMB_cloze: 'GMB/cloze.json',
  GMB_cloze_attachment: 'GMB/cloze_attachment.json',
  GMB_cloze_bitmarkMinueMinus: 'GMB/cloze_bitmark--.json',
  GMB_cloze_emoticons: 'GMB/cloze_emoticons.json',
  GMB_essay: 'GMB/essay.json',
  GMB_bitmark_example: 'GMB/bitmark_example.json',
  vocab1: 'vocab1.json',
  vocab2: 'vocab2.json',
  bookBits: 'book-bits.json',
  code: 'code.json',
  imageAudioVideo: 'image-audio-video.json',
  botActionResponse: 'bot-action-response.json',
  botActionTrueFalse: 'bot-action-true-false.json',
  botActionRatingNumber: 'bot-action-rating-number.json',
  vendorAmchart: 'vendor-amchart.json',
};

type KEYS = keyof typeof rawFiles;
type TEST_FILES = { [key in KEYS]: string };
const testFiles: TEST_FILES = {} as TEST_FILES;

for (const [k, v] of Object.entries(rawFiles)) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (testFiles as any)[k] = path.resolve(__dirname, '..', base, v);
}

export { testFiles };
